---
extends: default

ignore: |
  .venv/
  esphome/secrets.yaml
  esphome/.esphome/
  .esphome-sim/
  frodas-config/
  result

rules:
  document-start: disable
  truthy: disable
  line-length:
    max: 120
    allow-non-breakable-inline-mappings: true
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
